art_gallery_web/art_gallery_web/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('art_gallery_web.common.urls')),
                  path('auth/', include('art_gallery_web.gallery_auth.urls')),
                  path('arts/', include('art_gallery_web.gallery_app.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

art_gallery_web/art_gallery_web/gallery_app/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models

from art_gallery_web.gallery_auth.models import UserProfile


def is_negative(value):
    if value <= 0:
        raise ValidationError('The value must be positive')


# Create your models here.
class Arts(models.Model):
    name = models.CharField(max_length=15, blank=False)

    height = models.IntegerField(blank=False, validators=[is_negative, ])
    width = models.IntegerField(blank=False, validators=[is_negative, ])
    price = models.FloatField(blank=False, validators=[is_negative, ])

    description = models.TextField(blank=False)
    image = models.ImageField(upload_to='arts', blank=False)

    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.height} / {self.width}'


class Post(models.Model):
    text = models.TextField(blank=False)
    created_on = models.DateTimeField(auto_now_add=True)

    name = models.CharField(max_length=20, blank=False)
    email = models.EmailField(blank=False)

    art = models.ForeignKey(Arts, on_delete=models.CASCADE)

    def __str__(self):
        return f'Comment {self.text} by {self.name}'

art_gallery_web/templates/arts/art_create.html
{% extends 'mutual/base.html' %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'css/site.css' %}">

{% endblock %}
{% block site_title %}
    <h6 class="text-center">Add your new art</h6>
{% endblock %}
{% block content %}
     <div class="row">
                <div class="col-lg-3"></div>
                <div class="col-lg-6">
                    <form class="furniture-form" method="post" enctype="multipart/form-data" action="{% url 'create art' %}" >
                        {% csrf_token %}
                        {{ form }}

                        <input type="submit" value="Create" class="btn btn-secondary">
                    </form>
                </div>
                <div class="col-lg-3"></div>
            </div>
{% endblock %}

art_gallery_web/templates/arts/art_delete.html
{% extends 'mutual/base.html' %}
{% load static %}

{% block site_title %}
    <h1 class="text-center">Are you sure you want to delete - {{ art.name }}?</h1>
{% endblock %}
{% block content %}

    <div class="container-sm">

        <div class="alert alert-dark" role="alert">

            <form class="alert-link" method="post" action="{% url 'delete art' art.id %}">
                {% csrf_token %}
                <input type="submit" value="Confirm" class="btn btn-secondary"/>
            </form>


            <p></p>
            <a class="btn btn-secondary" href="{% url 'list arts' %}"> Back </a>

        </div>

    </div>

{% endblock %}

art_gallery_web/templates/arts/art_details.html
{% extends 'mutual/base.html' %}
{% load static %}

{% block content %}
    <section class="picture-item">

        <div class="photo"><img
                src="{{ art.image.url }}"
                alt="picture">
        </div>

        <blockquote>
            <p>{{ art.name }}</p>
            <p>{{ art.description }}</p>
            <h5>{{ art }}cm</h5>
            <h3 class="'price">{{ art.price }} $</h3>
            <a href="{% url 'user_profile' art.created_by_id %}" class="author">{{ art.created_by.username }}</a>
        </blockquote>
        <ul class="pictures-buttons">
            {% if can_modify %}
                <li><a class="button" href="{% url 'edit art' art.id %}">Edit</a></li>
                <li><a class="button" href="{% url 'delete art' art.id %}">Delete</a></li>
            {% endif %}
            <li><a class="button" href="{% url 'comment art' art.id %}">Comment</a></li>
        </ul>
        <hr>

        <div class="comments">
            {% if art.post_set.count > 0 %}

                <h4 >{{ post.post_set.count }}Comments </h4>


                {% for post_art in art.post_set.all %}

                    <div>
                        <p class="comments-date">{{ post_art.created_on }}</p>
                        <hr>
                        <p>{{ post_art.text }}</p>
                        <hr>
                        <p class="comments-name">{{ post_art.name }}</p>
                    </div>

                {% endfor %}

            {% else %}

                <h4>There are no comments</h4>
                <hr>

            {% endif %}
        </div>

    </section>
{% endblock %}

art_gallery_web/templates/arts/art_edit.html
{% extends 'mutual/base.html' %}
{% load static %}

{% block site_title %}
    <h6 class="text-center">Edit art:  {{ art.name }}</h6>
{% endblock %}
{% block content %}
     <div class="row">
                <div class="col-lg-3"></div>
                <div class="col-lg-6">
                    <form class="furniture-form" method="post" enctype="multipart/form-data" action="{% url "edit art" art.id %}" >
                        {% csrf_token %}
                        {{ form }}

                        <input type="submit" value="Edit" class="btn btn-secondary">
                    </form>
                </div>
                <div class="col-lg-3"></div>
            </div>
{% endblock %}

art_gallery_web/templates/arts/arts_list.html
{% extends 'mutual/base.html' %}
{% load static %}

{% block content %}
    <section class="pictures">
        <ul>
            {% for art_entry in arts %}
                <li>
                    <a href="{% url 'details arts' art_entry.id %}"><img src="{{ art_entry.image.url}}"
                                     alt="picture"></a>
                </li>
            {% endfor %}
        </ul>

    </section>
{% endblock %}